services:
  - type: static_site
    name: claude-template-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://claude-template-api.onrender.com